### ISSUE TITLE
Implement "assign", "get", "exists" and friends

### ISSUE THREAD

**Issue by skiadas** [PanthR/panthrLang#94]
Assign Syntax: `assign(x, value, pos = -1, envir = as.environment(pos), inherits = FALSE, immediate = TRUE)`

- `x` is a character vector and only its first entry is used (it must have at least one entry). Could probably use "string" type.
- `value` is the value that will be assigned to x
- `pos` can be:
    - `-1`, indicating the current environment
    - a positive integer, indicating an environment in the `search` path.
    - a character/string, indicating a name for an environment in the search path.
    - an environment.
- `envir` is for back-compatibility.
- `inherits` is a boolean. If TRUE, a binding is searched for in the enclosure up to the global environment, and an assignment happens where the binding is encountered (or the global environment)
- `immediate` is ignored.
- R notes suggest that a binding may be "locked" (lockBinding) or an environment may be locked.

Get syntax: `get(x, pos = -1, envir = as.environment(pos), mode = "any", inherits = TRUE)`

- `mode` suggests the "type" of the value to search for.
- If `inherits` is FALSE the search must stop at the current environment.

Multiple get: mget: `mget(x, envir = as.environment(-1), mode = "any", ifnotfound, inherits = FALSE)`

- Note the different inherits default.
- Allows "x" to be a vector of names. will form a list out of the matches.
- Only works if all are matched.
- mode can be length 1 or matching the x length. Then it applies component-wise
- ifnotfound is optional. It if exists it must be a list, of length 1 or equal to x. Its components will be used (matched by index, not name) to supplant values that were not found.
- returns a list of named values

exists syntax: `exists(x, where = -1, envir = , frame, mode = "any", inherits = TRUE)`
get0 syntax: `get0(x, envir = pos.to.env(-1L), mode = "any", inherits = TRUE, ifnotfound = NULL)`

- `where`, `envir` and `frame` are all ways to specify which environment to use (frame refers to call stack frames).
- `ifnotfound` is the value to return if the element is not found.

Must also implement `pos.to.env`.

Addresses parts of #80

**Comment by bwahl** [comment]
Note: Leaving `get0` and `mget` unimplemented for now, they seem low priority.
